apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: telegram-bot
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
    spec:
      containerConcurrency: 0
      containers:
        - image: ghcr.io/edude03/bot:00cb3d4b0a7c5e58f2093dabb994c05c8c8fa721
          name: user-container
          env:
            - name: TELEGRAM_TOKEN
              value: 5773440600:AAFCl8Wj4CK5RMsaSxEtB4n0xaQvJmW5eb8
            - name: EXTERNAL_URL
              value: https://telegram-bot.stable-diff.functions.melenion.com  
            - name: RUST_LOG
              value: debug
          readinessProbe:
            successThreshold: 1
            tcpSocket:
              port: 0
      enableServiceLinks: false
      timeoutSeconds: 300
  traffic:
    - latestRevision: true
      percent: 100
---
apiVersion: serving.knative.dev/v1alpha1
kind: DomainMapping
metadata:
  name: telegram-bot.functions.melenion.com
spec:
  ref:
    name: telegram-bot
    kind: Service
    apiVersion: serving.knative.dev/v1
  # tls:
  #   secretName: <cert-secret>
