name: Release
on:
  push:
    branches:
      - main

# permissions:
# contents: read
# packages: write

jobs:
  release:
    runs-on: ["ubuntu-latest"]
    steps:
      - uses: actions/checkout@v2
      - id: setup-pack
        uses: buildpacks/github-actions/setup-pack@v4.4.0
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: build-image
        run: |
          pack build ghcr.io/edude03/bot:${{ github.sha }} \
            --builder ghcr.io/melenion/rust-cnb-builder:latest \
            --publish
